HEADER = 'h1:nth-child(1)'

DEP_INPUT = '[data-qa-id="Main.SearchForm.DepInput"]'
ARR_INPUT = '[data-qa-id="Main.SearchForm.ArrInput"]'
FIRST_CITY_IN_LIST = '[data-qa-id="Main.CityList.CityListItem"]'
SWAP_CITY_BUTTON = '[data-qa-id="Main.SearchForm.SwapButton"]'

DATE_PICK_BUTTON = '[data-qa-id="Main.SearchForm.DatePickButton"]'
DATE_PICK_PLACEHOLDER = '(//span[@class="h-5 truncate text-gray-600"])[1]'
FIRST_MONTH_IN_LIST = '[data-qa-id="chocotravel-ui-calendar-first-month"]'
LAST_MONTH_IN_LIST = '[data-qa-id="chocotravel-ui-calendar-last-month"]'
TO_DATE_INPUT = '[data-qa-id="Main.Calendar.ToDateInput"]'
BACK_DATE_INPUT = '[data-qa-id="Main.Calendar.BackDateInput"]'
I_DONT_NEED_BACK = '[data-qa-id="Main.Calendar.NoBackTicket"]'
PREV_MONTH_BUTTON = '[data-qa-id="chocotravel-ui-calendar-prev-month-button"]'
NEXT_MONTH_BUTTON = '[data-qa-id="chocotravel-ui-calendar-next-month-button"]'
DAY_YESTERDAY = '[data-qa-id="chocotravel-ui-calendar-yesterday-day"]'
DAY_TODAY = '[data-qa-id="chocotravel-ui-calendar-today"]'
DAY_TOMORROW = '[data-qa-id="chocotravel-ui-calendar-tomorrow-day"]'
DAY_15TH = '[data-qa-id="chocotravel-ui-calendar-15-day"]'
DAY_360TH = '[data-qa-id="chocotravel-ui-calendar-360-day"]'
DAY_361TH = '[data-qa-id="chocotravel-ui-calendar-361-day"]'
CALENDAR_WINDIW = "(//section[contains(@class,'flex bg-white')])[1]"

PASSENGERS_DATA_INPUT = '[data-qa-id="Main.SearchForm.PassengersDataInput"]'
WINDOW_PASSENGERS = '.space-y-4.box-border'
CLASS_SPAN = '[data-qa-id="Main.SearchForm.CabinClassSpan"]'
PASSENGERS_AMOUNT = '[data-qa-id="Main.SearchForm.PassengersAmountSpan"]'
DEFAULT_PAX_BTN = '[data-id="default"]'
YOUNG_PAX_BTN = '[data-id="youth"]'
ECONOM_BTN = '[data-qa-id="Main.PasengersType.CabinEconom"]'
BUSINESS_BTN = '[data-qa-id="Main.PasengersType.CabinBusiness"]'
PASSENGERS_TITLE = '[data-qa-id="Main.PasengersType.PassengerTitle "]'
INCREASE_BTN = '[data-qa-id="Main.PasengersType.IncreaseButton"]'
DECREASE_BTN = '[data-qa-id="Main.PasengersType.DecreaseButton"]'
COUNTER = '[data-qa-id="Main.PasengersType.Counter"]'

COMPLEX_ROUTE_BUTTON = '[data-qa-id="Main.SearchForm.ComplexRouteButton"]'
REMOVE_COMPLEX_ROUTE_BUTTON = '[data-qa-id="Main.SearchForm.RemoveComplexRouteButton"]'

HOTEL_CHECKBOX = '[data-qa-id="Main.SearchForm.PickupHotelChechbox"]'

SEARCH_BUTTON = '[data-qa-id="Main.SearchForm.SearchButton"]'

HISTORY_1 = '(//button[contains(@type,"button")])[6]'
HISTORY_2 = '(//button[contains(@type,"button")])[7]'
HISTORY_3 = '(//button[contains(@type,"button")])[8]'

AVIA = '(//a[@class="avia js-link-event selected"])[1]'
SEARCH_RESULTS = '[data-qa-id="Main.SearchForm.SearchButton"]'